import type { NextPage } from 'next'
import AppBar from '@mui/material/AppBar';
import Head from 'next/head'
import Menu from './Menu'
import styles from '../styles/Home.module.css'
import Cart from './Cart'
import { Typography } from '@mui/material';
import { APP_CONSTANTS } from '../app/constants'
import WorkInProgress from './WIPComponents/WorkInProgress';

export const HomePage: NextPage = () => {
    const { WIP } = APP_CONSTANTS
    
    return (
      <div className={styles.container}>
        <Head>
          <title>Calppuccino App </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {WIP ? <WorkInProgress/>
        : (
          <>
        <AppBar color="default" style={{position: 'relative', padding: '1rem'}}> 
        <Typography component="div" variant="h5" style={{ textAlign: 'center', alignSelf:'center'}}>
          Bang For Bucks<sup>$</sup> Coffee
        </Typography>
      </AppBar>
      <Cart/>
      <Menu />
      </>
        )}

      </div>
    )
  }