import type { NextPage } from 'next'
import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import Head from 'next/head'
import Menu from './Menu'
import styles from '../styles/Home.module.css'
import Cart from './Cart'
import { Typography } from '@mui/material';

export const HomePage: NextPage = () => {

    return (
      <div className={styles.container}>
        <Head>
          <title>Calppuccino App </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <AppBar style={{position: 'relative', padding: '1rem'}}> 
          <Typography component="div" variant="h5" style={{ textAlign: 'center', alignSelf:'center'}}>
            Bang For Bucks<sup>$</sup> Coffee
          </Typography>
        </AppBar>
        <Cart/>
        <Menu />        
      </div>
    )
  }