import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export async function getServerSideProps() { 
  const res = await fetch(`http://localhost:3000/api/menu`)
  const { data } = await res.json()
  return { props: { data: data } }
}
const Home: NextPage = ({ data }: any) => {
  const menuItems = data  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Coffee Menu
        </h1>

        <p className={styles.description}>
          Pickup Address{' '}
          <code className={styles.code}></code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            {menuItems.map((item: any) => (
              <>
              <p>{item.itemName}</p>
              <p>{item.itemDescription}</p>
              <p>${item.itemTraits.price}</p>

              </>
            ))}
          </a>
        </div>
      </main>

    </div>
  )
}

export default Home
